enmusubi_server/config/routes.rb
Rails.application.routes.draw do

  get 'images' =>  'images#index'
    post  'images' =>  'images#create'
    get    'images/new' => 'images#new', :as => 'new_image'
    patch  'images/:textinfo_id'  =>  'images#update'
    put   'images/:textinfo_id' =>  'images#update'
    delete 'images/:textinfo_id'  =>  'images#destroy'
    get 'images/:textinfo_id' => 'images#show', :as => 'image'
    get 'images/:textinfo_id/edit'  =>  'images#edit', :as => 'edit_image'

    get 'users' =>  'users#index'
    post  'users' =>  'users#create'
    get 'users/:user_id/history' => 'users#history', :as => 'user_text_info'
    get    'users/new' => 'users#new', :as => 'new_user'
    patch  'users/:user_id'  =>  'users#update'
    put   'users/:user_id' =>  'users#update'
    delete 'users/:user_id'  =>  'users#destroy'
    get 'users/:user_id' => 'users#show', :as => 'user'
    get 'users/:user_id/edit'  =>  'users#edit', :as => 'edit_user'
    

    
    post  'texts' =>  'texts#create'
    get    'texts/new' => 'texts#new', :as => 'new_text'
    get 'texts/:univ'  => 'texts#index', :as => 'text_univ'
    patch  'texts/:textinfo_id/detail'  =>  'texts#update'
    put   'texts/:textinfo_id/detail' =>  'texts#update'
    delete 'texts/:textinfo_id/detail'  =>  'texts#destroy'
    get 'texts/:textinfo_id/detail' => 'texts#show', :as => 'text'
    get 'texts/:textinfo_id/edit'  =>  'texts#edit', :as => 'edit_text'
    post 'texts/search' => 'texts#search'

end

enmusubi_server/app/models/text.rb
class Text < ActiveRecord::Base
    primary_key = :textinfo_id
    attr_accessor :file
    belongs_to :user
end

enmusubi_server/app/controllers/texts_controller.rb
# encoding: utf-8
class TextsController < ApplicationController
  before_action :set_text, only: [:show, :edit, :update, :destroy]
  AWS.config(access_key_id: 'AKIAIPSMHHQZDEJKAGEA', secret_access_key: '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', region: 'ap-northeast-1')

  # GET /texts
  # GET /texts.json
  # @@univ = nil
  def index
    #  @texts = Text.all
     @texts = Text.where("univ = ? and status = ?", params[:univ], 1)
     @texts.each do |text| 
      if(text.teacher != nil)then
      text.teacher = text.teacher.force_encoding('utf-8')
      end
    if(text.lecture_name != nil)then
      text.lecture_name = text.lecture_name.force_encoding('utf-8')
      end
      if(text.textbook_name != nil) then
      text.textbook_name = text.textbook_name.force_encoding('utf-8')
      end
      if(text.comment != nil)then
      text.comment = text.comment.force_encoding('utf-8')
      end
      if(text.univ != nil)then
      text.univ = text.univ.force_encoding('utf-8')
      end 
      if(text.file_name != nil)then
      text.file_name = text.file_name.force_encoding('utf-8')
      end 
     
    end

    

      render :json => @texts.to_json(:include =>  {:user => { :only => ['link']}})
       #render :json => @texts
     # render :json => @texts.to_json(:include => [:image])
  end



  def search
    @textdatas = []
   if request.post? then
      # univ = @@univ
      @textdatas = Text.where("univ = ? and status = ? and (textbook_name like ? or lecture_name like ?)", params[:univ], 1, "%" + params[:textbook_lecture_name] + "%", "%" + params[:textbook_lecture_name] + "%") #現時点では，教科書検索しか想定していない．
      # @textdatas = Text.where("textbook_name like ?","%" + textbook_name + "%")
      @textdatas.each do |text| 
      if(text.teacher != nil)then
      text.teacher = text.teacher.force_encoding('utf-8')
      end
    if(text.lecture_name != nil)then
      text.lecture_name = text.lecture_name.force_encoding('utf-8')
      end
      if(text.textbook_name != nil) then
      text.textbook_name = text.textbook_name.force_encoding('utf-8')
      end
      if(text.comment != nil)then
      text.comment = text.comment.force_encoding('utf-8')
      end
      if(text.univ != nil)then
      text.univ = text.univ.force_encoding('utf-8')
      end
      if(text.file_name != nil)then
      text.file_name = text.file_name.force_encoding('utf-8')
      end
    end
      render :json => @textdatas.to_json(:include =>  {:user => { :only => ['link']}})
    end
  end

  # GET /texts/1
  # GET /texts/1.json
  def show
     @user = User.where("user_id = ?", @text.user_id)
    # @image = Image.where("image_id = ?", @text.image_id)
    #render :json => @user
if(@text.teacher != nil)then
      @text.teacher = @text.teacher.force_encoding('utf-8')
      end
      if(@text.lecture_name != nil)then
      @text.lecture_name = @text.lecture_name.force_encoding('utf-8')
      end
      if(@text.textbook_name != nil)then
      @text.textbook_name = @text.textbook_name.force_encoding('utf-8')
      end
      if(@text.comment != nil)then
      @text.comment = @text.comment.force_encoding('utf-8')
      end
      if(@text.univ != nil)then
      @text.univ = @text.univ.force_encoding('utf-8')
      end
      if(@text.file_name != nil)then
      @text.file_name = @text.file_name.force_encoding('utf-8')
      end
      @user.each do |use| 
     if(use.univ != nil)then
    use.univ = use.univ.force_encoding('utf-8')
    #render :json => use
      end
end
   # render :json => @text.to_json(:include => [:user])
   render :json => {:text => @text, :user => @user[0]}
   # {:moulding => @moulding, :material_costs => @material_costs }
  end

  # GET /texts/new
  def new
    @text = Text.new
  # @text.user_id = '1234' #params[:user_id]

    #アプリ側からpostで,そのユーザのIDが送られてくる．params[:user_id]で取得し，@text.user_idに格納する
  end

  # GET /texts/1/edit
  def edit
  end

  # POST /texts
  # POST /texts.json
  def create
    @text = Text.new(text_params)
    s3 = AWS::S3.new
    bucket = s3.buckets['ishidayouichi']
    file = text_params[:file]

    if(file != nil)then
    file_name = file.original_filename
    file_full_path="image/"+file_name
     
    object = bucket.objects[file_full_path]
    object.write(file ,:acl => :public_read)
    @text.file_name="http://s3-ap-northeast-1.amazonaws.com/ishidayouichi/image/#{file_name}"
    # respond_to do |format|
  end
      if @text.save
        #format.html { redirect_to text_path(@text), notice: 'Text was successfully created.' }
        # format.json { render :show, status: :created, location: @text }
         render :json => @text
      else
       # format.html { render :new }
        #format.json { render json: @text.errors, status: :unprocessable_entity }
        render :text => 'error'
      end
    #end
  end

  # PATCH/PUT /texts/1
  # PATCH/PUT /texts/1.json
  def update
  #  respond_to do |format|
      if @text.update(text_params)
       # format.html { redirect_to @text, notice: 'Text was successfully updated.' }
       # format.json { render :show, status: :ok, location: @text }
       if(@text.teacher != nil)then
       @text.teacher = @text.teacher.force_encoding('utf-8')
       end
       if(@text.lecture_name != nil)then
      @text.lecture_name = @text.lecture_name.force_encoding('utf-8')
      end
      if(@text.textbook_name != nil)then
      @text.textbook_name = @text.textbook_name.force_encoding('utf-8')
      end
      if(@text.comment != nil)then
      @text.comment = @text.comment.force_encoding('utf-8')
      end
      if(@text.univ != nil)then
      @text.univ = @text.univ.force_encoding('utf-8')
      end
        render :json => @text
      else
       # format.html { render :edit }
      #  format.json { render json: @text.errors, status: :unprocessable_entity }
      render :text => 'error'
      end
  #  end
  end

  # DELETE /texts/1
  # DELETE /texts/1.json
  def destroy
    @text.destroy
    respond_to do |format|
      format.html { redirect_to texts_url, notice: 'Text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text
      @text = Text.find(params[:textinfo_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_params
      params.require(:text).permit(:teacher, :univ, :user_id, :textinfo_id, :lecture_name, :textbook_name, :price, :comment, :file, :status)
    end
end

enmusubi_server/app/helpers/texts_helper.rb
module TextsHelper
end

enmusubi_server/app/views/texts/_form.html.erb
<%= form_for(@text) do |f| %>
  <% if @text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@text.errors.count, "error") %> prohibited this text from being saved:</h2>

      <ul>
      <% @text.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :lecture_name %><br>
    <%= f.text_field :lecture_name %>
  </div>
  <div class="field">
    <%= f.label :textbook_name %><br>
    <%= f.text_field :textbook_name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.number_field :status %>
  </div>
   <div class="field">
    <%= f.label :univ %><br>
    <%= f.text_field :univ %>
  </div>
  <div class="field">
    <%= f.label :teacher %><br>
    <%= f.text_field :teacher %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

enmusubi_server/app/views/texts/edit.html.erb
<h1>Editing text</h1>

<%= render 'form' %>

<%= link_to 'Show', @text %> |
<%= link_to 'Back', texts_path %>

enmusubi_server/app/views/texts/history.html.erb
<table>
  <thead>
    <tr>
      <th>user_id</th>
      <th>Lecture name</th>
      <th>Textbook name</th>
      <th>Price</th>
      <th>Comment</th>
      <th>Image</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @textdatas.each do |textdata| %>
      <tr>
        <td><%= textdata.user_id %></td>
        <td><%= textdata.lecture_name %></td>
        <td><%= textdata.textbook_name %></td>
        <td><%= textdata.price %></td>
        <td><%= textdata.comment %></td>
        <td><%= textdata.image %></td>
        <td><%= textdata.status %></td>
        <td><%= link_to 'Show', text %></td>
        <td><%= link_to 'Edit', edit_text_path(text) %></td>
        <td><%= link_to 'Destroy', text, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

enmusubi_server/app/views/texts/index.html.erb
<h1>Listing texts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Lecture name</th>
      <th>Textbook name</th>
      <th>Price</th>
      <th>Comment</th>
      <th>Image</th>
      <th>Status</th>
      <th>Univ</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @texts.each do |text| %>
      <tr>
        <td><%= text.user_id %></td>
        <td><%= text.lecture_name %></td>
        <td><%= text.textbook_name %></td>
        <td><%= text.price %></td>
        <td><%= text.comment %></td>
        <td><%= text.image %></td>
        <td><%= text.status %></td>
        <td><%= text.univ %></td>
        <td><%= text.teacher %></td>
        <td><%= link_to 'Show', text_path(text.textinfo_id) %></td>
        <td><%= link_to 'Edit', edit_text_path(text) %></td>
        <td><%= link_to 'Destroy', text, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br><br><br>

<%= form_tag( { controller: :texts, action: :search},
id: :textbook_lecture_name, class: :textbook_lecture_name) do %>
名前：
<%= text_field_tag :textbook_lecture_name, '', size: 30 %>
<%= submit_tag '送信' %>
<br/>
<% end %>

<br><br>



<%= link_to 'New Text', new_text_path %>

enmusubi_server/app/views/texts/new.html.erb
<h1>New text</h1>

<%= render 'form' %>

<%= link_to 'Back', texts_path %>

enmusubi_server/app/views/texts/search.html.erb
<table>
  <thead>
    <tr>
      <th>user_id</th>
      <th>Lecture name</th>
      <th>Textbook name</th>
      <th>Price</th>
      <th>Comment</th>
      <th>Image</th>
      <th>Status</th>
      <th>Univ</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @textdatas.each do |textdata| %>
      <tr>
        <td><%= textdata.user_id %></td>
        <td><%= textdata.lecture_name %></td>
        <td><%= textdata.textbook_name %></td>
        <td><%= textdata.price %></td>
        <td><%= textdata.comment %></td>
        <td><%= textdata.image %></td>
        <td><%= textdata.status %></td>
        <td><%= textdata.univ %></td>
        <td><%= textdata.teacher %></td>
        <td><%= link_to 'Show', textdata %></td>
        <td><%= link_to 'Edit', edit_text_path(textdata) %></td>
        <td><%= link_to 'Destroy', textdata, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

enmusubi_server/app/views/texts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @text.user_id %>
</p>

<p>
  <strong>Lecture name:</strong>
  <%= @text.lecture_name %>
</p>

<p>
  <strong>Textbook name:</strong>
  <%= @text.textbook_name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @text.price %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @text.comment %>
</p>

<p>
  <strong>Image:</strong>
  <%= @text.image %>
</p>

<p>
  <strong>Status:</strong>
  <%= @text.status %>
</p>

<p>
  <strong>Univ:</strong>
  <%= @text.univ %>
</p>
<p>
  <strong>Teacher:</strong>
  <%= @text.teacher %>
</p>
<%= link_to 'Edit', edit_text_path(@text) %> |
<%= link_to 'Back', texts_path %>