enmusubi_server/config/routes.rb
Rails.application.routes.draw do

  get 'images' =>  'images#index'
    post  'images' =>  'images#create'
    get    'images/new' => 'images#new', :as => 'new_image'
    patch  'images/:textinfo_id'  =>  'images#update'
    put   'images/:textinfo_id' =>  'images#update'
    delete 'images/:textinfo_id'  =>  'images#destroy'
    get 'images/:textinfo_id' => 'images#show', :as => 'image'
    get 'images/:textinfo_id/edit'  =>  'images#edit', :as => 'edit_image'

    get 'users' =>  'users#index'
    post  'users' =>  'users#create'
    get 'users/:user_id/history' => 'users#history', :as => 'user_text_info'
    get    'users/new' => 'users#new', :as => 'new_user'
    patch  'users/:user_id'  =>  'users#update'
    put   'users/:user_id' =>  'users#update'
    delete 'users/:user_id'  =>  'users#destroy'
    get 'users/:user_id' => 'users#show', :as => 'user'
    get 'users/:user_id/edit'  =>  'users#edit', :as => 'edit_user'
    

    
    post  'texts' =>  'texts#create'
    get    'texts/new' => 'texts#new', :as => 'new_text'
    get 'texts/:univ'  => 'texts#index', :as => 'text_univ'
    patch  'texts/:textinfo_id/detail'  =>  'texts#update'
    put   'texts/:textinfo_id/detail' =>  'texts#update'
    delete 'texts/:textinfo_id/detail'  =>  'texts#destroy'
    get 'texts/:textinfo_id/detail' => 'texts#show', :as => 'text'
    get 'texts/:textinfo_id/edit'  =>  'texts#edit', :as => 'edit_text'
    post 'texts/search' => 'texts#search'

end

enmusubi_server/app/models/user.rb
class User < ActiveRecord::Base
    primary_key = :user_id
    has_many :texts
end

enmusubi_server/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @users.each do |user| 
      if(user.name != nil)then
      user.name = user.name.force_encoding('utf-8')
      end
      if(user.univ != nil)then
      user.univ = user.univ.force_encoding('utf-8')
      end
    end
    render :json => @users
  end

  def history
    @textdatas = Text.where(user_id: params[:user_id]) # params[:user_id] 
    #これもpostでそのユーザのIDが送られてくる．
    #それをparams[:user_id]で取得する．
    @textdatas.each do |text| 
      if(text.teacher != nil)then
      text.teacher = text.teacher.force_encoding('utf-8')
      end
      if(text.lecture_name != nil)then
      text.lecture_name = text.lecture_name.force_encoding('utf-8')
      end
      if(text.textbook_name != nil) then
      text.textbook_name = text.textbook_name.force_encoding('utf-8')
      end
      if(text.comment != nil)then
      text.comment = text.comment.force_encoding('utf-8')
      end
      if(text.univ != nil)then
      text.univ = text.univ.force_encoding('utf-8')
      end
    end
    render :json => @textdatas
  end



  # GET /users/1
  # GET /users/1.json
  def show
    if(@user.name != nil)then
      @user.name = @user.name.force_encoding('utf-8')
      end
    if(@user.univ != nil)then
      @user.univ = @user.univ.force_encoding('utf-8')
      end
     render :json => @user
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
if(User.where(user_id: @user.user_id) == [])then#一致するuserがなければ#
    # respond_to do |format|
    if(@user.name != nil)then
      @user.name = @user.name.force_encoding('utf-8')
      end
    if(@user.univ != nil)then
      @user.univ = @user.univ.force_encoding('utf-8')
      end
      if @user.save
          # format.html { redirect_to @user, notice: 'User was successfully created.' }
       # format.json { render :show, status: :created, location: @user }
      render :json => @user
      else
      #  format.html { render :new }
      #  format.json { render json: @user.errors, status: :unprocessable_entity }
         render :text => 'error'
      end
    #end
  else
     render :json  => User.where(user_id: @user.user_id) #response ok 
  end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    #respond_to do |format|
      if @user.update(user_params)
      # format.html { redirect_to @user, notice: 'User was successfully updated.' }
       # format.json { render :show, status: :ok, location: @user }
       if(@user.name != nil)then
      @user.name = @user.name.force_encoding('utf-8')
      end
    if(@user.univ != nil)then
      @user.univ = @user.univ.force_encoding('utf-8')
      end
       render :json => @user
      else
      #  format.html { render :edit }
       # format.json { render json: @user.errors, status: :unprocessable_entity }
       render :text => 'error'
      end
    #end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :link, :univ, :user_id)
    end
end

enmusubi_server/app/helpers/users_helper.rb
module UsersHelper
end

enmusubi_server/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :univ %><br>
    <%= f.text_field :univ %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

enmusubi_server/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

enmusubi_server/app/views/users/history.html.erb
<table>
  <thead>
    <tr>
      <th>user_id</th>
      <th>Lecture name</th>
      <th>Textbook name</th>
      <th>Price</th>
      <th>Comment</th>
      <th>Image</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @textdatas.each do |textdata| %>
      <tr>
        <td><%= textdata.user_id %></td>
        <td><%= textdata.lecture_name %></td>
        <td><%= textdata.textbook_name %></td>
        <td><%= textdata.price %></td>
        <td><%= textdata.comment %></td>
        <td><%= textdata.image %></td>
        <td><%= textdata.status %></td>
        <td><%= link_to 'Show', textdata %></td>
        <td><%= link_to 'Edit', edit_text_path(textdata) %></td>
        <td><%= link_to 'Destroy', textdata, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

enmusubi_server/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Link</th>
      <th>Univ</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.link %></td>
        <td><%= user.univ %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
        <td><%= link_to 'history', user_text_info_path(user.user_id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



<%= link_to 'New User', new_user_path %>

enmusubi_server/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

enmusubi_server/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User_ID:</strong>
  <%= @user.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>


<p>
  <strong>Link:</strong>
  <%= @user.link %>
</p>

<p>
  <strong>Univ:</strong>
  <%= @user.univ %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>